globals = {
        "mods",
        "game",
        "util",
        "data",
        "remote",
        "settings",
        "commands",
        "global",
        "rendering",
        "table_size",
        "script",
        "defines",
        "mapProcessorG",
        "pheromoneUtilsG",
        "aiAttackWaveG",
        "aiPlanningG",
        "aiPredicatesG",
        "constantsG",
        "chunkProcessorG",
        "chunkPropertyUtilsG",
        "chunkUtilsG",
        "interopG",
        "mapUtilsG",
        "mathUtilsG",
        "movementUtilsG",
        "playerUtilsG",
        "squadAttackG",
        "aiDefenseG",
        "stringUtilsG",
        "unitGroupUtilsG",
        "unitUtilsG",
        "baseUtilsG",
        "queryUtilsG"
}

max_line_length = false