local util = require("BiterFunctions")

local makeBiter = util.makeBiter
local createSuicideAttack = util.createSuicideAttack
local makeResistance = util.makeResistance

data:extend({
    makeBiter({name = "small-suicide-biter",
               health = 30,
               movement = 0.25,
               healing = 0.01,
               scale = 0.55,
               tint1 = {r=0.6, g=0.0, b=0.70, a=0.8},
               tint2 = {r=0.7, g=0.0, b=0.72, a=0.4},
               explosion = "blood-explosion-small"},
              createSuicideAttack({ area = 3.5,
                                    damage = 60,
                                    explosion = "explosion",
                                    scorchmark = "small-scorchmark"})),
    makeBiter({name = "medium-suicide-biter",
               health = 125,
               movement = 0.24,
               healing = 0.01,
               scale = 0.75,
               tint1 = {r=0.6, g=0.0, b=0.70, a=0.8},
               tint2 = {r=0.7, g=0.0, b=0.72, a=0.4},
               explosion = "blood-explosion-small"},
              createSuicideAttack({ area = 4.5,
                                    damage = 140,
                                    explosion = "medium-explosion",
                                    scorchmark = "small-scorchmark"}),
              {makeResistance("physical", 4, 0),
               makeResistance("explosion", 0, 10),
               makeResistance("fire", 0, -50)}),
    makeBiter({name = "big-suicide-biter",
               health = 425,
               movement = 0.23,
               scale = 1.05,
               tint1 = {r=0.6, g=0.0, b=0.70, a=0.8},
               tint2 = {r=0.7, g=0.0, b=0.72, a=0.4},
               explosion = "blood-explosion-big"},
              createSuicideAttack({ area = 5.5,
                                    damage = 500,
                                    explosion = "big-explosion",
                                    scorchmark = "small-scorchmark"}),
              {makeResistance("physical", 8, 0),
               makeResistance("explosion", 0, 10),
               makeResistance("fire", 0, -30)}),
    makeBiter({name = "behemoth-suicide-biter",
               health = 1200,
               movement = 0.22,
               scale = 1.25,
               tint1 = {r=0.6, g=0.0, b=0.70, a=0.8},
               tint2 = {r=0.7, g=0.0, b=0.72, a=0.4},
               explosion = "blood-explosion-big"},
              createSuicideAttack({ area = 7.5,
                                    damage = 3000,
                                    explosion = "massive-explosion",
                                    scorchmark = "small-scorchmark"}),
              {makeResistance("physical", 8, 20),
               makeResistance("explosion", 10, 20),
               makeResistance("fire", 0, -10)})
})